#!/usr/bin/ansible-playbook --inventory=inventory
- name: "Konductor | Provision UPI Infra | build-tfprovider-binaries.yml"
  hosts: localhost
  vars_files:
    - 'vars/vault.yml'
    - 'vars/global.yml'
  vars:
    module: "build-terraform-providers"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  tasks:
    - name: Import terraform providers bundle collection tasks
      import_role:
        name: configure-terraform-for-disconnected
        tasks_from: collect-tf-binaries-bundle.yml

