#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision-upi-infra | Build Infra Resources'
  hosts: local
  vars:
    module: "ovirt"
    instance_type: "infra-resources"
    state_provider: "local"
    tf_module_path: "{{ dir_terraform }}/{{ module }}/{{ instance_type }}"
    ansible_name_module: " Konductor | Provision UPI Infra Nodes | {{ module }} | {{ instance_type }}"
    instance_group: "infra"
    instance_dir_suffix: "-node-search"
    search_dir_suffix: "node-search"
    instance_file_suffix: "-search"
    instance_inventory_file: "infra"
    instance_role_groups: "{{ ['lb','registry'] }}"
  vars_files:
    - vars/vault.yml
    - vars/global.yml

  roles:
    - { role: build-upi-resources, search_vms: 'true' } 
