#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision-upi-infra | Build Cluster Resources'
  hosts: local
  vars:
    module: "ovirt"
    instance_type: "cluster-resources-template"
    state_provider: "local"
    tf_module_path: "{{ dir_terraform }}/{{ module }}/{{ instance_type }}"
    ansible_name_module: " Konductor | Provision UPI Cluster Nodes | {{ module }} | {{ instance_type }}"
  vars_files:
    - vars/global.yml

  tasks:
    - name: '{{ ansible_name_module }} | import_role | RHCOS Template provision '
      import_role:
        name: build-upi-resources 
        tasks_from: rhcos-template.yml

