#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision UPI Infra | bundle-ocp-images-for-artifactory.yml' 
  hosts: localhost 
  become: yes
  vars_files:
    - 'vars/global.yml'
  vars:
    ansible_python_interpreter: /usr/bin/python3
    module: "bundle-operators"
    ansible_name_module: " Konductor | Provision UPI Infra | {{ module }}"
    dir_bundle_location: "/data/bundle/artifactory"
    ocp_release_image_registry: "quay.io"
    ocp_release_image_repository: "openshift-release-dev/ocp-release"
    ocp_release_version: "4.7.0"
    ocp_release_arch: "x86_64"

  tasks:

    - name: Create bundle for artifactory
      import_role:
        name: mirror-ocp4-content-artifactory 
        tasks_from: bundle-ocp-images.yml

