#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: '{{ name_vendor }} | Koffer | dns-client.yml' 
  hosts: "{{ target | d('new*') }}" 
  become: true
  vars_files:
    - 'vars/vault.yml'
    - 'vars/global.yml'
  vars:
    module: "dnsclients"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  tasks:
    - name: Include role if appropriate
      include_role: 
        name: ipaclient
      when:
        - register_client_with_freeipa is defined
        - register_client_with_freeipa | bool 
