#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision UPI Infra  | loadbalancer.yml' 
  hosts: newlb
  become: true
  vars_files:
    - 'vars/global.yml'
  vars:
    module: "loadbalancer"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  tasks:
    - name: '{{ ansible_name_module }} | import_role | config-host-to-containerized-service'
      import_role:
        name: config-host-to-run-containerized-service

    - name: '{{ ansible_name_module }} | import_role | haproxy-loadbalancer-service'
      import_role:
        name: haproxy-loadbalancer-service

