#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision UPI Infra  | loadbalancer.yml' 
  hosts: newlb
  become: true
  vars_files:
    - 'vars/global.yml'
  vars:
    module: "loadbalancer"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  tasks:
    - name: '{{ ansible_name_module }} | Install and configure LB'
      block:
        - name: '{{ ansible_name_module }} | Import LB installation role'
          import_role:
            name: loadbalancer
          register: lb_installed

        - name: '{{ ansible_name_module }} | copy LB config template into place'
          template:
            src: "templates/loadbalancer/haproxy.cfg.j2"
            dest: "/etc/haproxy/haproxy.cfg"
            force: yes
            backup: yes
          register: haproxycfg_copied

        - name: '{{ ansible_name_module }} | Ensure the firewall-cmd is installed'
          yum:
            name: "firewalld,python-firewall"
          register: firewalld_pkgs_installed

        - name: '{{ ansible_name_module }} | Ensure SELinux ports are properly configured'
          seport:
            ports: 6443,22623,80,443,9000
            proto: "{{ item }}"
            setype: http_port_t
            state: present
          loop:
            - tcp
            - udp

        - name: '{{ ansible_name_module }} | Ensure Firewalld is enabled'
          systemd:
            name: firewalld
            state: started
            enabled: yes

        - name: '{{ ansible_name_module }} | Enable appropriates port on public zone'
          firewalld:
            port: "{{ item }}"
            permanent: yes
            zone: public
            immediate: yes
            state: enabled
          loop:
            - 6443/tcp
            - 22623/tcp
            - 443/tcp
            - 80/tcp
            - 9000/tcp

        - name: '{{ ansible_name_module }} | Enable appropriates port on internal zone'
          firewalld:
            port: "{{ item }}"
            permanent: yes
            zone: internal
            immediate: yes
            state: enabled
          loop:
            - 6443/tcp
            - 22623/tcp
            - 443/tcp
            - 80/tcp
            - 9000/tcp

        - name: '{{ ansible_name_module }} | Enable the HAProxy service'
          systemd:
            name: haproxy
            enabled: true

        - name: '{{ ansible_name_module }} | Restart the HAProxy service'
          systemd:
            name: haproxy
            state: restarted

