#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision UPI Infra | nginx.yml' 
  hosts: "{{ groups.nginx_hosts | default(groups.newregistry) }}"
  become: yes
  vars_files:
    - 'vars/vault.yml'
    - 'vars/global.yml'
  vars:
    module: "nginx"
    ansible_name_module: " Konductor | Provision UPI Infra | {{ module }}"
  tasks:
    - name: '{{ ansible_name_module }} | Install and Nginx to host ignition files' 
      when: 
        - provision_nginx is defined
        - provision_nginx | bool
      block:
        - name: '{{ ansible_name_module }} | import_role | config-host-to-containerized-service'
          import_role:
            name: config-host-to-run-containerized-service

        - name: '{{ ansible_name_module }} | import_role | config-nginx-service'
          import_role:
            name: config-nginx-service

