#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: 'RedHat | Konductor | provision-cluster.yml'
  hosts: localhost
  vars_files:
    - vars/global.yml
  tasks:
    - set_fact:
        create_template: "{{ create_template | d(omit)}}"
        coreos_vm_template_id: "{{ coreos_vm_template_id | d('') }}"
      delegate_to: localhost
      delegate_facts: yes

- import_playbook: provision-rhcos-template.yml     # Provision UPI infra nodes
  when:
    - (create_template is defined and create_template | bool) or coreos_vm_template_id is not defined or (coreos_vm_template_id is defined and coreos_vm_template_id == '' )
- import_playbook: setup-cluster-resources.yml   # Setup Terraform to provision UPI cluster resources
- import_playbook: build-upi-cluster.yml   # Use terraform to provision cluster ressources
- import_playbook: update-lb-confg.yml   # Update LB config to reflect newly added cluster resurces
  
