#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision UPI Infra | push-ocp-images-to-registry.yml' 
  hosts: localhost 
  become: yes
  vars_files:
    - 'vars/vault.yml'
    - 'vars/global.yml'
  vars:
    module: "push ocp images to registry"
    bundle_file_location: "/data/bundle/openshift-bundle.tar.xz"
    release_image_repository: "openshift-release-dev"

  tasks:
    - name: '{{ ansible_name_module }} | Trust Registry CA on controller'
      when:
        - trust_registry_ca is defined
        - trust_registry_ca | bool
      block: 
        - name: '{{ ansible_name_module }} | Copy registry CA to /etc/pki/ca-trust/source/anchors/'
          copy:
            src: "{{ registry_ca_local_dir }}/{{ registry_ca_local_name }}"
            dest: /etc/pki/ca-trust/source/anchors/{{ registry_ca_local_name }}
            force: yes

        - name: '{{ ansible_name_module }} | command | Update the trust store'
          command: update-ca-trust extract
          register: registry_ca_trusted

    - name: '{{ ansible_name_module }} | Push bundle content into registry'
      import_role:
        name: mirror-ocp4-content-artifactory
        tasks_from: unbundle-ocp-images.yml
      vars:
        reg_port: "{{ registry_host_port }}"

