#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision UPI Infra | Gather instance facts'
  hosts: local
  gather_facts: no
  vars_files:
    - vars/global.yml
  tasks:
    - setup:

    - name: "ovirt | ensure that the coreos template id to use exist"
      fail:
        msg: "The variable coreos_vm_template_id or generated_coreos_template_id cannot be undefined"
      when:
        - coreos_vm_template_id is not defined or coreos_vm_template_id == ''
        - generated_coreos_template_id is not defined or generated_coreos_template_id == '' 

- name: ' Konductor | Provision UPI Infra | Build Ovirt Nodes'
  hosts: localhost
  vars:
    module: "ovirt"
    instance_type: "cluster-resources"
    state_provider: "local"
    tf_module_path: "{{ dir_terraform }}/{{ module }}/{{ instance_type }}"
    ansible_name_module: " Konductor | Provision UPI Infra | {{ module }} | {{ instance_type }}"
    instance_group: "cluster"
    instance_role_groups: "{{ ['bootstrap','masters','workers'] }}" 
    instance_dir_suffix: "-node-search"
    search_dir_suffix: "node-search"
    instance_file_suffix: "-search"
    static_inventory_file: "inventory-cluster"
    
  vars_files:
    - vars/global.yml
  roles:
    - { role: setup-terraform-module, vm_template_id: "{{ coreos_vm_template_id if coreos_vm_template_id is defined and coreos_vm_template_id != '' else generated_coreos_template_id }}", create_cluster_inventory: "true" }
