#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision UPI Infra | Gather instance facts'
  hosts: local
  gather_facts: no
  tasks:
    - setup:

    - name: Assert that an nginx host exists
      assert:
        that:
          - "'registry' in groups.keys() or 'nginx_hosts' in groups.keys() or 'newregistry' in groups.keys()"
          - "(groups.registry is defined and groups.registry | length > 0) or (groups.newregistry is defined and groups.newregistry | length > 0) or (groups.nginx_hosts is defined and groups.nginx_hosts | length > 0)"
        msg: "An nginx host is required. It can be an existing one if a new one is not being created."
      when:
        - "'http' in rhcos_image_url"

- name: ' Konductor | Provision UPI Infra | Build Ovirt Nodes'
  hosts: localhost
  vars:
    module: "ovirt"
    instance_type: "rhcos-vm-template"
    template_type: "rhcos"
    template_disk_size: "120"
    create_rhcos_template: true
    state_provider: "local"
    tf_module_path: "{{ dir_terraform }}/{{ module }}/{{ instance_type }}"
    ansible_name_module: " Konductor | Provision UPI Infra | {{ module }} | {{ instance_type }}"
    
  vars_files:
    - vars/vault.yml
    - vars/global.yml
  tasks:
    - name: '{{ ansible_name_module }} | import_role | RHCOS Template provision setup'
      import_role:
        name:  setup-terraform-module
        tasks_from: template.yml
