#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision UPI Infra | Gather instance facts'
  hosts: local
  gather_facts: no
  vars_files:
    - vars/vault.yml
    - vars/global.yml
  tasks:
    - setup:
    - name: "ovirt | ensure that the RHEL template id to use exist"
      fail:
        msg: "The variable vm_template_id or generated_template_id cannot be undefined"
      when:
        - vm_template_id is not defined or vm_template_id == ''
        - generated_template_id is not defined or generated_template_id == ''

- name: ' Konductor | Provision UPI Infra | Build Ovirt Nodes'
  hosts: localhost
  vars:
    module: "ovirt"
    instance_type: "infra-resources"
    state_provider: "local"
    tf_module_path: "{{ dir_terraform }}/{{ module }}/{{ instance_type }}"
    ansible_name_module: " Konductor | Provision UPI Infra | {{ module }} | {{ instance_type }}"
    instance_group: "infra"
    instance_role_groups: "{{ ['lb','registry'] }}"
    instance_dir_suffix: "-node-search"
    search_dir_suffix: "node-search"
    instance_file_suffix: "-search"
    vm_template_id: "{{ generated_template_id | default(vm_template_id, true) }}"
  vars_files:
    - vars/vault.yml
    - vars/global.yml
  roles:
    - { role: setup-terraform-module, search_vms: 'true' }
