#!/usr/bin/ansible-playbook --inventory=inventory
- name: "Konductor | Provision UPI Infra | terraform.yml"
  hosts: localhost
  vars_files:
    - 'vars/global.yml'
  vars:
    module: "terraform"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
    ver_terraform_package: "0.12.30"
  tasks:
    - name: Import terraform installation tasks
      import_role:
        name: configure-terraform-for-disconnected
        tasks_from: install-terraform-connected.yml
