#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Konductor | Provision UPI Infra | unbundle-operators.yml' 
  hosts: localhost 
  become: yes
  vars_files:
    - 'vars/vault.yml'
    - 'vars/global.yml'
  vars:
    module: "registry"
    ansible_name_module: " Konductor | Provision UPI Infra | {{ module }}"
  pre_tasks:
    - name: '{{ ansible_name_module }} | yum | install required packages on registry '
      yum:
        name:
          - tar 
          - podman
          - jq
          - lzma
          - python-backports-lzma
          - xz-devel
        state: present
      when:
        - not inventory_hostname in ['localhost', 'local']

  tasks:
    - name: '{{ ansible_name_module }} | file:directory | Ensure the images directory exist'
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ dir_bundle_staging }}"

    - name: '{{ ansible_name_module }} | Process operator bundle | on registry '
      block: 
        - name: '{{ ansible_name_module }} | file:directory | Ensure the staging directory exist'
          file:
            path: "{{ dir_bundle_staging }}"
            state: directory
            mode: 0755

        - name: '{{ ansible_name_module }} | copy | operator bundles files to registry '
          copy:
            src: "{{ bundle_file_location }}"
            dest: "{{ dir_bundle_staging }}/{{ bundle_file_location | basename }}"
            mode: 0777
            force: yes
          when:
            - not inventory_hostname in ['localhost', 'local']
          register: op_bundle_copied

        - name: '{{ ansible_name_module }} | set_fact | bundle file location facts '
          set_fact:
            local_bundle_dir: "{{ dir_bundle_staging if not inventory_hostname in ['localhost', 'local'] else bundle_file_location | dirname }}"

        - name: '{{ ansible_name_module }} | unarchive:xz | original operator bundle on registry '
          unarchive:
            src: "{{ local_bundle_dir }}/{{ bundle_file_location | basename }}"
            remote_src: yes
            dest: "{{ dir_bundle_staging }}"
            mode: 0755
          register: op_unbundle_out

        - name: '{{ ansible_name_module }} | set_fact | registry image files load facts '
          set_fact:
            local_registry_dir: "{{ dir_bundle_staging }}/docker/registry/v2"

        - name: '{{ ansible_name_module }} | command:podman:load | load'
          command: podman load -i {{ dir_bundle_staging }}/container-registry-image.tar
          register: registry_container_loaded

        - name: '{{ ansible_name_module }} | set_fact | Set loaded registry container image name '
          set_fact:
            temp_container_registry_image: "{{ registry_container_loaded.stdout.split(' ')[2] }}"
          when:
            - registry_container_loaded is defined
            - registry_container_loaded.rc == 0
            - not registry_container_loaded.failed | bool
            - registry_container_loaded is defined
            - registry_container_loaded.stdout != ""
              
        - name: '{{ ansible_name_module }} | podman:run | Start registry container '
          command: >
            podman run -d --name {{ registry_container_name }} \
            -p 5000:5000 -v {{ dir_bundle_staging }}:/var/lib/registry:z \
            {{ temp_container_registry_image }}
          when:
            - temp_container_registry_image is defined
            - temp_container_registry_image != ""

        - name: '{{ ansible_name_module }} | command | generate authfile for registry'
          no_log: true
          command: > 
            podman login -u {{ registry_admin_username }} -p {{ registry_admin_password }} \
               --authfile {{ hostvars[inventory_hostname].ansible_env.HOME }}/.docker/config.json \
               {{ registry_host_fqdn }}:{{ registry_host_port }}
          register: authfile_created

        - name: '{{ ansible_name_module }} | stat | check if source secret is included in bundle'
          stat:
            path: "{{ dir_bundle_staging }}/source-operators-pull-secret.json"
          register: source_pullsecret_check

        - name: '{{ ansible_name_module }} | set_fact |  operator_registry_pull_secret_file if undefined'
          set_fact:
            operator_registry_pull_secret_file: "{{ dir_bundle_staging }}/source-operators-pull-secret.json"
          when:
            - not operator_registry_pull_secret_file is defined or (operator_registry_pull_secret_file == "")
            - source_pullsecret_check.stat.exists

        - name: '{{ ansible_name_module }} | set_fact |  authfile for registry'
          set_fact:
            registry_auth_config: "{{ hostvars[inventory_hostname].ansible_env.HOME }}/.docker/config.json"
          when:
            - authfile_created is defined

        - name: '{{ ansible_name_module }} | jq | generate combined authfile for registry'
          shell: > 
            jq -c --argjson \
              var "$(jq .auths {{ registry_auth_config }})" \
              '.auths += $var' {{ operator_registry_pull_secret_file }} \ 
              | jq '.' > {{ dir_bundle_staging }}/operators-registry.json

        - name: '{{ ansible_name_module }} | command:oc adm | load images to registry '
          command: > 
            oc adm catalog mirror \
              localhost:5000/{{ source_operators_repository }}/{{ source_operator_index }}:{{ source_operator_index_tag }} \
             {{ registry_host_fqdn }}:{{ registry_host_port }}/{{ local_olm_repository }} \
              -a {{ dir_bundle_staging }}/operators-registry.json \
              --filter-by-os="linux/amd64" \
              --insecure=true
          when:
            - authfile_created is defined
          register: registry_loaded

  post_tasks:
    - name: '{{ ansible_name_module }} | podman:rm | Remove mirror-registry '
      command: podman rm -f {{ registry_container_name | d('mirror-registry') }}

    - name: '{{ ansible_name_module }} | file:absent | bundles staging directories'
      file:
        state: absent 
        path: "{{ item }}"
      with_items: 
        - "{{ dir_bundle_staging }}"
      when:
        - registry_loaded is defined
        - registry_loaded.changed | bool
        - not registry_loaded.failed | bool
