---
# tasks file for build-upi-infra-resources
####### Terraform Init
- name: '{{ ansible_name_module }} | shell | terraform init'
  shell: terraform init
  args:
    chdir: "{{ tf_module_path }}"
  with_items:
    - "{{ tf_module_path }}"

####### Terraform Apply
- name: '{{ ansible_name_module }} | command | terraform | apply'
  terraform:
    project_path: "{{ tf_module_path }}"
    force_init: true
    state: present
  ignore_errors: true
  register: tf_apply

- name: '{{ ansible_name_module }} | command | wait for all vms to be created before running next tasks'
  wait_for:
    timeout: 150
  delegate_to: localhost

