---
# tasks file for build-upi-infra-resources
- name: '{{ ansible_name_module }} | add_host | import_tasks build-vms-and-disks.yml'
  import_tasks: build-vms-and-disks.yml

- name: '{{ ansible_name_module }} | add_host | import_tasks search_vms.yml'
  import_tasks: search_vms.yml 
  when:
    - search_vms is defined 
    - search_vms | bool

- name: '{{ ansible_name_module }} | add_host | import_tasks search_mac_addresses.yml'
  import_tasks: search_mac_addresses.yml 
  when:
    - search_mac_addresses is defined 
    - search_mac_addresses | bool

