---
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local 
          ansible_user: root
    localhost:
      hosts:
        localhost:
          ansible_connection: local 
          ansible_user: root
    lb:
      hosts:
        container-lb:
          ansible_connection: local 
          ansible_user: root
      vars:
        vm_memory: 4096
        vm_cpu_cores: 2
        vm_cpu_sockets: 2
    registry:
      hosts:
        container-registry:
          ansible_connection: local 
          ansible_user: root
      vars:
        vm_memory: 4096
        vm_cpu_cores: 2
        vm_cpu_sockets: 2
        attach_additional_disks: true
        additional_disks:
          - { name: containers, size: 30, mount: '/var/lib/containers' }
          - { name: registry, size: 300, mount: '/var/lib/registry' }
    dns:
      hosts:
    dhcp:
      hosts:
    bootstrap:
      hosts:
      vars:
        vm_cpu_cores: 1
        vm_cpu_sockets: 4
        vm_memory: 16384
        ignition_file_suffix: "bootstrap.ign"
        custom_script: "/tmp/custom-script.json"
    masters:
      hosts:
      vars:
        vm_cpu_cores: 1
        vm_cpu_sockets: 4
        vm_memory: 16384
        ignition_file_suffix: "master.ign"
        custom_script: "/tmp/custom-script.json"
    workers:
      hosts:
      vars:
        vm_cpu_cores: 1
        vm_cpu_sockets: 2
        vm_memory: 8192
        ignition_file_suffix: "worker.ign"
        custom_script: "/tmp/custom-script.json"
