---
# tasks file for config-nginx-service
- name: '{{ ansible_name_module }} | Install and Nginx to host ignition files'
  set_fact:
    nginx_name: "{{ 'nginx' if ansible_distribution_major_version == '8' else 'rh-nginx116' }}"
    config_file_suffix: "rhel{{ ansible_distribution_major_version | default('7', true) }}.conf.j2"
    nginx_root_dir: "{{ '/usr/share/nginx/html' if ansible_distribution_major_version == '8' else nginx_root_directory }}"
    nginx_conf_file: "{{ '/etc/nginx/nginx.conf' if ansible_distribution_major_version == '8' else nginx_conf }}"

- name: '{{ ansible_name_module }} | Install Nginx available in repo '
  yum:
    name: "{{ nginx_name }}"
    state: present

- name: '{{ ansible_name_module }} | shell:systemctl list-unit-file | get nginx service name '
  shell: "systemctl list-unit-files | grep {{ nginx_name }} | awk '{print $1}'"
  register: nginx_service

- name: '{{ ansible_name_module }} | template |  nginx.conf '
  template:
    src: "nginx-{{ config_file_suffix }}"
    dest: "{{ nginx_conf_file }}"
    mode: '755'
    backup: yes

- name: '{{ ansible_name_module }} | file |  ign-repos '
  file:
    path: "{{ nginx_root_dir }}/{{ ign_repos_name }}"
    state: directory
    mode: 755

- name: '{{ ansible_name_module }} | file |  rhcos-isos '
  file:
    path: "{{ nginx_root_dir }}/{{ ign_iso_repos_name }}"
    state: directory
    mode: 755
  when:
    - host_rhcos_images is defined
    - host_rhcos_images | bool

- name: '{{ ansible_name_module }} | Ensure Nginx Service is started and enabled '
  systemd:
    name: "{{ nginx_service.stdout }}"
    state: started
    enabled: yes
  when:
    - nginx_service
    - nginx_service.rc == 0
    - not nginx_service.stdout == ""
