# Ovirt Cluster Info
ovirt_url: ''
ovirt_username: ''
ovirt_password: ''
storage_domain_id: ''
cluster_id: ''
vm_template_id: ''
dns_search: ''
dns_servers: ''
vm_user: 'root'
vm_rootpw: '!'
host_subdomain: ''
vm_cpu_cores: 1
vm_cpu_sockets: 1
vm_memory: 2048
nic_boot_proto: 'dhcp'
base_domain: ''
additional_disks: []
attach_additional_disks: true

# Vm Instances to build
authorized_ssh_key: "{{ sshkeys_pub_string }}" 

#Vm to skip
vm_skip_list:
  - localhost

# Bash ENV Lookups
local_home: "{{ lookup('env', 'HOME') }}"
local_user: "{{ lookup('env', 'USER') }}"

# SSH Keys
sshkeys_priv_file: "{{ local_home }}/.ssh/id_rsa_cluster_deploy"
sshkeys_priv_string: "{{ lookup('file', '{{ sshkeys_priv_file }}') }}"
sshkeys_pub_file: "{{ local_home }}/.ssh/id_rsa_cluster_deploy.pub"
sshkeys_pub_string: "{{ lookup('file', '{{ sshkeys_pub_file }}') }}"

# Load balancer Config
kube_api_port: 6443
machine_config_server_port: 22623

# Registry Config
registry_host_fqdn:
registry_secret: ''
registry_admin_username: ''
registry_admin_password: ''
secure_registry: false
enable_authz_on_registry: true
generate_selfsigned_registry_certfiles: false

